[package]
name = "zk-neural-rust-core"
version = "0.1.0"
edition = "2024"


[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
image = "0.25.6"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tflitec = "0.6.0"
thiserror = "2.0.12"
